quiz_maker.quiz_type.*:
  type: config_entity
  label: 'Quiz type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

quiz_maker.question_type.*:
  type: config_entity
  label: 'Question type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

quiz_maker.question_answer_type.*:
  type: config_entity
  label: 'Question Answer type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

quiz_maker.quiz_result_type.*:
  type: config_entity
  label: 'Quiz Result type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

quiz_maker.question_response_type.*:
  type: config_entity
  label: 'Question Response type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
